version: ~> 1.0

os: windows
language: shell

import:
  - source: portapps/portapps:.travis/configs/install.yml
  - source: portapps/portapps:.travis/configs/build.yml
  - source: portapps/portapps:.travis/configs/set-version.yml
  - source: portapps/portapps:.travis/configs/git-config.yml
  - source: portapps/portapps:.travis/configs/deploy.yml
  - source: portapps/portapps:.travis/configs/notifs.yml

deploy:
  api_key:
    secure: a763y2z4bHv0X+83PgA3hWJjZXMNomklOAnMg5OrzjOKOPVMFumdqWRHLmkDXWEjZe37xQuZ14WjC30yXNv5tRv/O1MTPCcuN/hD0fRKdA6QJQb4K+N79ofEZd4h5d/fPh7woBL8dRbIg2qEz8pwZJaJATusdHX8dS8gkHqkKnbckq/snhRa/7KB3Hq7eR0WFkKUfb8SFbeLD9ohHOtp5ja6eJua3I1yjiqGWNJSuJBGIJflBcGZ6WsK4aEuK3tuYDLrkQA7XGjDejV238CN9JI8/IHB7UlG9PfZfESF8UBXB++SfOqxmUurcktUwHa9o3vz1Mu+K1tma1h9lBSBm4AoF4+42LrDSOcWpooQPfCOE4KMPXwGRugRSDblehUjprVQNvVByQTErPTMcMcGO65oxICDS0q3tipOeqtpi5iSbkjg3dMHTmjZSMWHPRLEXv0uWMKpclkYwGqJjN8NFyk1C3LMMmZ6mUYi6nABVE0syqBRk1TjZowPpSapHIWrWxDgDfn/sm7AUflqX7kaqOz/qPerK9fQKQLaDghn6xaNMKnM/dV97rKfnEtPA36+vYuZiQF1FXrwVXP0x2MWy7OI6QWDqwho2k3g/07nyhnn27c7AmgyOAVLI7CYFTtjJmfQ6EsI8S1/86idbEyz7hL/yDOkr8Q3LIAyCfE//CM=
