version: ~> 1.0

os: windows
language: shell

env:
  global:
    - secure: 0itJx29hDSjIxBSeOV4x1qXCcjhnNRmM/7ngrPijlvNIuTx2GYJTAKC/9AyDSei0m+tH7AnFeklRCE6kGYhEBhvC7j1wTkrA53VsezZGD80vCkHRB/NfofNXs3bBSO7LndFeJ9nvTPtsZOCAVq5Cwzd9u5r8y7iYsdIHdik8SIk3BAlBDDDdXgoGQjns80k+79cslXJ+PIA5TVWEIpXiY/BRKzFr3Yf+o11OgEpHrjrSlPzoh2xbjIlY29mN0qIR6MW2VbLikkmpGnyoYbhvMEUpYOKcV0QcsVtJ51sa2QBTtv3E6pDR77VcDWvJcTJS4UsqVq9lLYb8gpj6YdTa7uysfMENSKXmLqrs8VpPv6RXFCXM0iuAK4z/y8nixfF8lbtKyWttl8VGODrHOCi4N8tOoxEIgn7GfgXf1ojkxA5GJIzRvJ7HUyKz0H3jc7HGSqBbQDjlYNzxtuceY1xTU2dkmwMg0QJ3Tw91B0hZ4bg1Q4z3Vpp2+W/hr2HcbrBEDbpUheLJOB/YpNJ7tW3tl1Oc7BzOpyyx0hIqP4YHFFYB72ncZnIgSOds0UIiUj6gmIozVX06dQcSEGL0Cg1cYX4eQVC6CLWfiH8TSdep/gXKIe+ghlke+1zS8O4Whui4WtBBhYHpqw53+C5ymMNtLBjtwO3q/aYHJ+fGgQ0VpZw= # GITHUB_TOKEN

import:
  - source: portapps/portapps:.travis/configs/install.yml
  - source: portapps/portapps:.travis/configs/build.yml
  - source: portapps/portapps:.travis/configs/set-version.yml
  - source: portapps/portapps:.travis/configs/git-config.yml
  - source: portapps/portapps:.travis/configs/deploy.yml
  - source: portapps/portapps:.travis/configs/notifs.yml
