name: dump

on:
  workflow_dispatch:
  push:

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1
